// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210724202652_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Domain.Entity.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<long>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0807223-3083-4548-a93a-e47f76c5d519"),
                            Brand = "Volkswagen",
                            Mileage = 100234L,
                            Model = "Golf",
                            Year = 2009
                        },
                        new
                        {
                            Id = new Guid("f3d6fac5-4790-4442-8eeb-b8e6a206bcf3"),
                            Brand = "Volkswagen",
                            Mileage = 59001L,
                            Model = "Polo",
                            Year = 2010
                        },
                        new
                        {
                            Id = new Guid("257a8c5d-f245-4729-87aa-2c233773e944"),
                            Brand = "Volkswagen",
                            Mileage = 10234L,
                            Model = "Jetta",
                            Year = 2015
                        },
                        new
                        {
                            Id = new Guid("3f7f9306-2ad9-4c72-ac39-62636b530a4c"),
                            Brand = "Volkswagen",
                            Mileage = 26050L,
                            Model = "Gol",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("a46f5ce0-8a6d-401b-a36b-1f9427bf3e78"),
                            Brand = "Fiat",
                            Mileage = 14200L,
                            Model = "Uno",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("7f71a709-59d3-4daf-931e-3c03cf8abb88"),
                            Brand = "Fiat",
                            Mileage = 5502L,
                            Model = "Argo",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("84290c09-f58d-4de6-a221-31060fae5260"),
                            Brand = "Fiat",
                            Mileage = 34508L,
                            Model = "Mobi",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("f3856abd-53f2-443f-ba18-144dc184fa54"),
                            Brand = "Fiat",
                            Mileage = 85745L,
                            Model = "Siena",
                            Year = 2012
                        },
                        new
                        {
                            Id = new Guid("06fd1c59-a97c-46ce-b7ff-ab95bf651ad5"),
                            Brand = "Chevrolet",
                            Mileage = 66520L,
                            Model = "Cruze",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("2f0d2710-8f9c-42f7-9781-776867d1b62c"),
                            Brand = "Chevrolet",
                            Mileage = 33200L,
                            Model = "Onix",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("d922d888-0ee2-4024-a6d8-ed1ee3a6b587"),
                            Brand = "Chevrolet",
                            Mileage = 66504L,
                            Model = "Tracker",
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("ba77451a-2829-4901-8fe7-29095d4b97cf"),
                            Brand = "Chevrolet",
                            Mileage = 468500L,
                            Model = "Spin",
                            Year = 2015
                        },
                        new
                        {
                            Id = new Guid("c3531139-fe10-4536-94fe-9bcb834948fe"),
                            Brand = "Chevrolet",
                            Mileage = 22500L,
                            Model = "Camaro",
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("497a39c6-0b30-422b-882d-cb893eca327a"),
                            Brand = "Chevrolet",
                            Mileage = 56252L,
                            Model = "Cobalt",
                            Year = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
